# Generated by Django 5.2.1 on 2025-05-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_administrativa', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('activo_fijo', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
            ],
        ),
    ]
